name: Release Promotion Guard

permissions:
  contents: read

on:
  pull_request:
    branches:
      - release/dev
      - release/itt
      - release/uat
      - release/prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  promotion-check:
    name: "Validate Release Promotion"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate feature promotion
        run: |-
          set -e

          TARGET="${GITHUB_EVENT_PULL_REQUEST_BASE_REF}"
          COMMIT="${{ github.event.pull_request.head.sha }}"
          DEFAULT_BRANCH="${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH}"

          # print statetements for sanity checks
          echo "[DEBUG] GITHUB REPOSITORY: ${github.repository}"
          echo "[DEBUG] SOURCE BRANCH: ${GITHUB_HEAD_REF}"
          echo "[DEBUG] TARGET BRANCH: ${GITHUB_BASE_REF}"
          echo "[DEBUG] PR COMMIT: ${GITHUB_SHA}"
          echo "[DEBUG] HEAD COMMIT: ${COMMIT}"
          echo "[DEBUG] DEFAULT BRANCH: ${DEFAULT_BRANCH}"

          git fetch origin --prune

          check_in () {
              local commit=$1
              local branch=$2
              if git merge-base --is-ancestor "$commit" "origin/$branch"; then
              echo "✅ Commit exists in $branch"
              else
              echo "❌ Commit does NOT exist in $branch, please first merge your branch into $branch before promoting to $TARGET"
              exit 1
              fi
          }

          case "$TARGET" in

              release/dev)
              echo "ℹ️ No checks for dev, you can promote directly"
              ;;

              release/itt)
              check_in "$COMMIT" "release/dev"
              ;;

              release/uat)
              check_in "$COMMIT" "release/itt"
              ;;

              release/prod)
              check_in "$COMMIT" "release/uat"
              check_in "$COMMIT" "$DEFAULT_BRANCH"
              ;;

              *)
              echo "ℹ️ No promotion rules"
              ;;
          esac

        env:
          GITHUB_EVENT_PULL_REQUEST_HEAD_REF: ${{ github.event.pull_request.head.ref }}

          GITHUB_EVENT_PULL_REQUEST_BASE_REF: ${{ github.event.pull_request.base.ref }}

          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
